services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    container_name: ${PROJECT_NAME:-nestjs-module}
    restart: unless-stopped
    user: root
    network_mode: host
    # environment:
      # - http_proxy=http://127.0.0.1:7897
      # - https_proxy=http://127.0.0.1:7897
    volumes:
      # 挂载整个项目目录到容器的/app目录
      - .:/app
      # 排除node_modules，使用镜像中预安装的依赖
      - /app/node_modules
      # 挂载日志目录
      - ./logs:/var/log
      # 挂载 PM2 日志目录
      - ./logs/pm2-logs:/root/.pm2/logs

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'

    # 在这里启动应用
    command: ['/usr/local/bin/startup.sh']

    # 调试模式：取消注释下面的命令来保持容器运行
    # command: tail -f /dev/null
